[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"

[deploy.lifecycle]
postDeploy = "echo 'Deployment complete!'"

[[services]]
name = "pixel-dropper"
